"""add owner_id field to tg_channel table

Revision ID: e8b9c5049d94
Revises: f9a1ddd0ff0e
Create Date: 2024-02-02 02:01:39.507073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b9c5049d94'
down_revision: Union[str, None] = 'f9a1ddd0ff0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgchannels', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tgchannels', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tgchannels', type_='foreignkey')
    op.drop_column('tgchannels', 'owner_id')
    # ### end Alembic commands ###
